config/routes.rb
Rails.application.routes.draw do
  get 'cloud_accounts/show'

  get 'cloud_accounts/new'

  get 'cloud_accounts/edit'

  get 'cloud_accounts/delete'

  get 'cloud_accounts/index'

  get 'cloud_account/index'

  devise_for :users

  resources :dashboard, only: [:index]
  resources :schedules
  resources :users, except: [:new]

  get 'rdsstart', to: 'skejulers#rdsstart'
  get 'rdsstop', to: 'skejulers#rdsstopt'
  get 'ec2start', to: 'skejulers#ec2start'
  get 'ec2stop', to: 'skejulers#ec2stop'

  root 'high_voltage/pages#show', id: 'about'
  match ':controller(/:action(/:id))',:via =>[:get, :post]

end

app/models/schedule.rb
# require 'ice_cube_methods'

class Schedule < ApplicationRecord
# class Schedule < ActiveRecord::Base

  belongs_to :user


end

app/controllers/schedules_controller.rb
# require '../skejuler-aws/lib/skejuler/aws/rds.rb'
include IceCubeMethods


class SchedulesController < ApplicationController

  before_action :authenticate_user!

  def index
    @schedule = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])


  end

  def new
    @schedule = current_user.schedules.build #Schedule.new
  end

  def create
    @schedule = current_user.schedules.build(schedule_params)
    # @schedule.user = User.first
    respond_to do |format|
      if @schedule.save



        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }

        action_value = @schedule.action

        sch_options

        case action_value
          when "start_rds"
            puts "starting rds"
            rdsstart
          when "stop_rds"
            puts "stopping rds"
            rdsstop
          when "start_ec2"
            puts "Starting Ec2"
            ec2start
          when "stop_ec2"
            puts "Stopping Ec2"
            ec2stop
          when "none"
          format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
    end
    end

  def edit
      @schedule=Schedule.find(params[:id])
  end


  def update
    respond_to do |format|
      @schedule=Schedule.find(params[:id])
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @schedule.destroy
    @status_update = Schedule.find(params[:id])
    if @status_update.present?
      @status_update.destroy
    end
    flash[:notice] = "Schedule was successfully Deleted"
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was destroyed.' }
      format.json { head :no_content }
    # end
    # redirect_to root_path
    end
    end


def schedule_params
  params.require(:schedule).permit(:name, :remarks, :enabled, :dat_tme, :from_date, :from_time, :repeat, :occurs, :snapshotid, :snapshotname, :timezone, :repeatdays, :repeatweek, :weekdays,  :repeatmonth, :monthdays, :repeats_every_X_hour, :repeats_every_X_week, :cloud, :region, :action, :instanceid)
end






  def rdsstart

  rds = Aws::RDS::Resource.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_API_KEY'],
      secret_access_key: ENV['AWS_SECRET_KEY']
  )
  # ::Skejuler::Aws::Rds::Mylog.start(rds,)

  # redirect_to root_path and return

end

def rdsstop

  rds = Aws::RDS::Resource.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_API_KEY'],
      secret_access_key: ENV['AWS_SECRET_KEY']
  )
  logger.debug rds.inspect
  ::Skejuler::Aws::Rds::Mylog.stop(rds)
  redirect_to root_path
end

def ec2start
  ec2_client = Aws::EC2::Client.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_API_KEY'],
      secret_access_key: ENV['AWS_SECRET_KEY']
  )

  ::Skejuler::Aws::Rds::Mylog.start(ec2_client)
  redirect_to root_path
end

def ec2stop
  ec2_client = Aws::EC2::Client.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_API_KEY'],
      secret_access_key: ENV['AWS_SECRET_KEY']
  )

  ::Skejuler::Aws::Rds::Mylog.stop(ec2_client)
  redirect_to root_path
end


  def sch_options

    if @schedule.repeat != false
      schedule = IceCube::Schedule.new(@schedule.dat_tme)
    end
      if @schedule.repeat == true
        schedule = IceCube::Schedule.new(@schedule.dat_tme)
        if @schedule.occurs == "daily"
          schedule.add_recurrence_rule IceCube::Rule.daily(@schedule.repeatdays)
          puts "schedules are"
          puts schedule.first(10)
        end
        if @schedule.occurs == "weekly"
          if @schedule.weekdays == 8
            schedule.add_recurrence_rule IceCube::Rule.weekly(@schedule.repeatweek)
        end
        if @schedule.weekdays != 8
          schedule.add_recurrence_rule IceCube::Rule.weekly(@schedule.repeatweek).day(@schedule.weekdays)
        end
          puts "schedules are"
          puts schedule.first(10)
        end
        if @schedule.occurs == "monthly"
          schedule.add_recurrence_rule IceCube::Rule.monthly(@schedule.repeatmonth)
          puts "schedules are"
          puts schedule.first(10)
        end

    end
  end
end

app/views/schedules/_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script>
<%= bootstrap_form_for schedule, html: {class: 'form-horizontal', novalidate: 'novalidate'} do |f| %>
  <div class="row">
    <div class="span6">
      <%= f.text_field :name, class: 'span4' %>
      <%= f.text_field :remarks, class: 'span4' %>
      <%= f.check_box :enabled, {checked: true} %>
      <p>Schedule</p>
    <div class="form-inline">
      <%= f.datetime_select :dat_tme, {default: Time.now} %>
        <div class="form-inline">
        <%= f.time_zone_select :timezone %>
        </div>
    <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>
    </div>
    </div>
    <div class="span6">
      <%= render partial: 'options_daily', locals: {f: f} %>
    </div>
    <div class="span6">
      <%= f.select :cloud, Schedule::CloudOptions %>
      <%= f.select :region, Schedule::RegionOptions %>
    </div>
    <div class="span6">
      <%= f.select :action, Schedule::ActionOptions %>
      <%= f.text_field :instanceid, class: 'span4' %>
    </div>
    <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>
  </div>
  <div class="form-actions">
    <%= f.submit 'Schedule',class: 'btn btn-primary btn-md' %>
  </div>
<% end %>

<% content_for :first_styles do %>
    <css>

      #occurs_options {display:none;}
      #repeats_daily_options {display:none;}
      #repeats_weekly_options {display:none;}
      #repeats_monthly_options {display:none;}
      #repeats_yearly_options {display:none;}


    </css>
<% end %>

app/views/schedules/_options_daily.html.erb
<script>
  $(document).ready(function () {
          $('.showButton').click(function () {
              if ($(this).is(":checked")) {
                  $(".targetDIV").show();
                  $('#div' + $(this).attr('target')).show('slide');}
              else {
                  $(".targetDIV").hide();
                  $('#div' + $(this).attr('target')).hide('slide');
              }


          });
  });


$(document).ready(function(){

  $("#daily").click(function(){
    $("#daily_options").show();
    $("#weekly_options").hide();
    $("#monthly_options").hide();
    $("#yearly_options").hide();
  });
  $("#weekly").click(function(){
    $("#daily_options").hide();
    $("#weekly_options").show();
    $("#monthly_options").hide();
    $("#yearly_options").hide();
  });
  $("#monthly").click(function(){

    $("#daily_options").hide();
    $("#weekly_options").hide();
    $("#monthly_options").show();
    $("#yearly_options").hide();
  });
  $("#yearly").click(function(){
    $("#daily_options").hide();
    $("#weekly_options").hide();
    $("#monthly_options").hide();
    $("#yearly_options").show();
  });
});

</script>





<div class="form-inline">
  <!--<input type="checkbox" class="showButton"  target="1">Repeat?</in>-->
  <%= f.check_box :repeat, class: "showButton", target: "1" %>
  <!--<tr>-->
    <!--<th>Repeat Method</th>-->
  <!--<td><%= f.radio_button :snapshotid,false,id: "repeatfalse",checked:"checked" %> No Repeatition</td>-->
    <!--<td><%= f.radio_button :snapshotid,true,id: "repeattrue" %> Repeat</td>-->
    <!--</tr>-->
  <!--&lt;!&ndash;<input type="checkbox" class="showButton"  target="2">Button 2&ndash;&gt;-->
  <!--&lt;!&ndash;<input type="checkbox" class="showButton"  target="3">Button 3&ndash;&gt;-->
</div>
<!--</br>-->
<!--<div id="div1" class="targetDiv">Please Select the Schedule you want to repeat<br />-->
  <!--</br>-->
  <!--<select name="occurs">-->
    <!--<option value="daily" class="showButton" target="4">Daily</option>-->
    <!--<option value="weekly" class="showButton" target="5">Weekly</option>-->
    <!--<option value="monthly" class="showButton" target="4">Monthly</option>-->
    <!--<option value="yearly" class="showButton" target="4">Yearly</option>-->
  <!--</select>-->
  <!--&lt;!&ndash;<input type="checkbox" class="showButton" target="4">Daily&ndash;&gt;-->
  <!--&lt;!&ndash;<input type="checkbox" class="showButton" target="5">Weekly&ndash;&gt;-->
  <!--&lt;!&ndash;<input type="checkbox" class="showButton" target="6">Monthly&ndash;&gt;-->
  <!--&lt;!&ndash;<input type="checkbox" class="showButton" target="7">Yearly&ndash;&gt;-->
  <!--<div id="div4" class="targetDiv"></div>-->
  <!--<div id="div5" class="targetDiv"><%= render partial: 'repeats_weekly_options', locals: {f: f}%>.</div>-->
  <!--<div id="div6" class="targetDiv"><%= render partial: 'repeats_monthly_options', locals: {f: f}%></div>-->
  <!--<div id="div7" class="targetDiv">Yearly schedule</div>-->
<!--</div>-->
<!--<div id="div2" class="targetDiv">Content of div 2.<br/>-->
  <!--<button class="showButton" target="9">open 9</button>-->
<!--</div>-->
<!--<div id="div3" class="targetDiv">Content of div 3.<br/>-->
  <!--&lt;!&ndash;<button class="showButton" target="6">open 6</button>&ndash;&gt;-->
  <!--&lt;!&ndash;<div id="div6" class="targetDiv">Content of div 6.<br />&ndash;&gt;-->
    <!--<button class="showButton" target="9">open 9</button>-->
    <!--<button class="showButton" target="10">open 10</button>-->
    <!--<div id="div9" class="targetDiv">Content of div 9.<br/>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
<!--<hr />-->

<style>
.targetDiv {
display: none;
}
#daily_options {
  display: none;
}
#weekly_options {
  display: none;
}
#monthly_options {
  display: none;
}
#yearly_options {
  display: none;
}
</style>


<div id="div1" class="targetDiv">
  <div class="form-inline">
<tr>
  <td ><%= f.radio_button :occurs,"daily",id: "daily" %>Daily</td>
  <td ><%= f.radio_button :occurs,"weekly",id: "weekly" %>Weekly</td>
  <td ><%= f.radio_button :occurs,"monthly",id: "monthly" %>Monthly</td>
  <td ><%= f.radio_button :occurs,"yearly",id: "yearly" %>Yearly</td></td>
</tr>
  </div>
<div id="daily_options" >
  <%= f.number_field :repeatdays%>
</div>


<div id="weekly_options">
  <%= f.number_field :repeatweek  %>
  <!--<td ><%= f.check_box :weekdays, {}, "Sunday"%>Sunday</td>-->
  <!--<td ><%= f.check_box :weekdays, {},"Monday" %>Monday</td>-->
  <!--<td ><%= f.check_box :weekdays, {},"Tuesday" %>Tuesday</td>-->
  <!--<td ><%= f.check_box :weekdays, {},"Wednesday"%>Wednesday</td></td>-->
  <%= f.select :weekdays, Schedule::DaysOfWeeks %>
</div>

  <div id="monthly_options" >
    <%= f.number_field :repeatmonth %>
    <%= f.select :monthdays, Schedule::DaysOfTheMonth%>
  </div>

  <div id="yearly_options" >
    <h5>Yearly Options</h5>
  </div>
</br>
  </div>


  <!-- -#= f.check_box :repeat   #:input_html => { :id => "sd"}-->
  <!--#revision{:style => "display: none"}-->
  <!-- -#= render partial: 'repeats_weekly', locals: {f: f}-->
  <!-- -#= f.select :occurs, Schedule::RepeatsOptions-->
  <!--#event_daily{:style => "display: none"}-->
  <!-- -#= render partial: 'repeats_daily_options', locals: {f: f}-->
  <!--#event_weekly{:style => "display: none"}-->
  <!-- -#= f.select :snapshotname, Schedule::DaysOfWeeks-->
  <!-- -#= render partial: 'repeats_weekly_options', locals: {f: f}-->
  <!--#event_monthly-->
  <!-- -#= render partial: 'repeats_monthly_options', locals: {f: f}-->
  <!--#event_yearly{:style => "display: none"}-->
  <!-- -#= render partial: 'repeats_yearly_options', locals: {f: f}-->
  <!-- -#=f.text_field :repeats_every_X_month, {style: 'width:auto;'}-->
  <!-- -#%section#dvPassport{:style => "display: none"}-->
  <!-- -#  = f.text_field :name-->



  <!-- -#= f.date_field :from_date, :placeholder => "MM/DD/YYYY", :input_html => {:class => "datepicker date-picker"}, :label => "Select Date"-->
  <!-- -#= f.date_field :from_date, :placeholder => "MM/DD/YYYY", :input_html => {:class => "datepicker date-picker"}, :label => "Select Date"-->
  <!--.input-append.bootstrap-timepicker-->
  <!-- -#= f.time_select :from_time, {default: Time.now}, :input_html => { :id => "starts_at", :class => "input-append bootstrap-timepicker"}, :label => " Select Time "-->
  <!-- -#= f.time_zone_select :from_time, {:minute_step => 15}, {style: 'width:auto;'}-->
  <!-- -#= f.date_select :from_date, {}, {style: 'width:auto;'}-->

app/views/schedules/_repeats_daily_options.html.haml
%fieldset{id: 'repeats_daily_options', class: 'event_option'}
  -#= f.number_field :repeats_every_X_day         #repeats_every_n_days

app/views/schedules/_repeats_monthly_options.html.haml
-#%fieldset{ id: 'repeats_monthly_options', class: 'event_option'}
-#  = f.number_field :repeats_every_X_month                #repeats_every_n_months
-#  = f.select :repeats_monthly, Schedule::RepeatMonthlyOptions
-#  #event_repeats_monthly_each.control-group
-#    %label.control-label Each
-#    .form-inline
-#      - Schedule::DaysOfTheMonth.each do |day_of_the_month|
-#        = label_tag "event_repeats_monthly_each_days_of_the_month_#{day_of_the_month}", day_of_the_month, :class => 'checkbox inline' do
-#          = check_box_tag "event[repeats_monthly_each_days_of_the_month][#{day_of_the_month}]", day_of_the_month, f.object.repeats_monthly_each_days_of_the_month.include?(day_of_the_month), {:name => "event[repeats_monthly_each_days_of_the_month][]"}
-#          = day_of_the_month
-#      = hidden_field_tag "event[repeats_monthly_each_days_of_the_month][]", ""
-#  #event_repeats_monthly_on.control-group
-#    %label.control-label On the
-#    .form-inline
-#      - Schedule::Ordinals.each_with_index do |ordinal,index|
-#        = label_tag "event_repeats_monthly_on_ordinals_#{ordinal}", ordinal, :class => 'checkbox inline' do
-#          = check_box_tag "event[repeats_monthly_on_ordinals][#{ordinal}]", ordinal, f.object.repeats_monthly_on_ordinals.include?(ordinal), {:name => "event[repeats_monthly_on_ordinals][]"}
-#          = Schedule::HumanOrdinals[index]
-#      = hidden_field_tag "event[repeats_monthly_on_ordinals][]", ""
-#      %hr
-#    %label.control-label
-#      - Schedule::DaysOfTheWeek.each do |day_of_the_week|
-#        = label_tag "event_repeats_monthly_on_days_of_the_week_#{day_of_the_week}", day_of_the_week.humanize, :class => 'checkbox inline' do
-#          = check_box_tag "event[repeats_monthly_on_days_of_the_week][#{day_of_the_week}]", day_of_the_week, f.object.repeats_monthly_on_days_of_the_week.include?(day_of_the_week), {:name => "event[repeats_monthly_on_days_of_the_week][]"}
-#          = day_of_the_week.humanize
-#      = hidden_field_tag "event[repeats_monthly_on_days_of_the_week][]", ""

app/views/schedules/_repeats_weekly.html.erb
<label for="dailyevent">
  <input type="checkbox" id="dailyevent" />
  Daily?
</label>




<!--<div >-->
  <!--<label><input type="checkbox" id="inputbox" name="colorCheckbox" value="daily"> daily </label>-->
  <!--<label><input type="checkbox" id="inputbox" name="colorCheckbox" value="weekly"> weekly </label>-->
  <!--<label><input type="checkbox" id="inputbox" name="colorCheckbox" value="monthly"> monthly </label>-->
  <!--<label><input type="checkbox" id="inputbox" name="colorCheckbox" value="yearly"> yearly </label>-->
<!--</div>-->

app/views/schedules/_repeats_weekly_options.html.haml
-#%fieldset{ id: 'repeats_weekly_options', class: 'event_option'}
-#  = f.number_field :repeats_every_X_week
-#
-#  .control-group
-#    %label.control-label
-#    .controls
-#      -#=f.check_box_tag "event[repeats_weekly_each_days_of_the_week_mask][#{days_of_weeks}]"
-#
-#
-#      - Schedule::DaysOfTheWeek.each do |day_of_the_week|
-#        = label_tag "event_repeats_weekly_each_days_of_the_week_#{day_of_the_week}", day_of_the_week.humanize, :class => 'checkbox inline' do
-#          = check_box_tag "event[repeats_weekly_each_days_of_the_week][#{day_of_the_week}]", day_of_the_week, f.object.repeats_weekly_each_days_of_the_week.include?(day_of_the_week), {:name => "event[repeats_weekly_each_days_of_the_week][]"}
-#          = day_of_the_week.humanize
-#      = hidden_field_tag "event[repeats_weekly_each_days_of_the_week][]", ""

app/views/schedules/_repeats_yearly_options.html.haml
%fieldset{ id: 'repeats_yearly_options', class: 'event_option'}
  = f.number_field :repeats_every_n_years
  .control-group
    %label.control-label Each
    .controls
      - Schedule::MonthsOfTheYear.each do |month_of_the_year|
        = label_tag "event_repeats_yearly_each_months_of_the_year_#{month_of_the_year}", month_of_the_year.humanize, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_yearly_each_months_of_the_year][#{month_of_the_year}]", month_of_the_year, f.object.repeats_yearly_each_months_of_the_year.include?(month_of_the_year), {:name => "event[repeats_yearly_each_months_of_the_year][]"}
          = month_of_the_year.humanize
      = hidden_field_tag "event[repeats_yearly_each_months_of_the_year][]", ""
  = f.check_box :repeat
  #event_repeats_yearly_on_options.control-group
    %label.control-label On the
    .controls
      - Schedule::Ordinals.each_with_index do |ordinal,index|
        = label_tag "event_repeats_yearly_on_ordinals_#{ordinal}", ordinal, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_yearly_on_ordinals][#{ordinal}]", ordinal, f.object.repeats_yearly_on_ordinals.include?(ordinal), {:name => "event[repeats_yearly_on_ordinals][]"}
          = Schedule::HumanOrdinals[index]
      = hidden_field_tag "event[repeats_yearly_on_ordinals][]", ""
      %hr
      - Schedule::DaysOfTheWeek.each do |day_of_the_week|
        = label_tag "event_repeats_yearly_on_days_of_the_week_#{day_of_the_week}", day_of_the_week.humanize, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_yearly_on_days_of_the_week][#{day_of_the_week}]", day_of_the_week, f.object.repeats_yearly_on_days_of_the_week.include?(day_of_the_week), {:name => "event[repeats_yearly_on_days_of_the_week][]"}
          = day_of_the_week.humanize
      = hidden_field_tag "event[repeats_yearly_on_days_of_the_week][]", ""

app/views/schedules/_schedule.html.erb
<div align="center">
<form class="group">
<!--<button type="submit" style="background-color:#007acc;color:white" onclick= class="btn btn-default">New Schedule</button>-->
<%= link_to 'New Schedule',  schedules_index_path,class: 'button alt' %>
</form>
</div>

app/views/schedules/calendar.html.haml
#calendar{:style => 'margin:1em 0;'}
    
- content_for :last_javascripts do
  :javascript
      $('#calendar').fullCalendar({
        eventSources: [
          // your event source
          {
              url: '/event_instances.json',
              data: {
                  custom_param1: 'something',
                  custom_param2: 'somethingelse'
              },
              error: function() {
                  alert('there was an error while fetching events!');
              }
          }
          // any other sources...
        ]
      });

app/views/schedules/edit.html.erb
<h2>Edit the Schedule </h2>

<%= render 'form', schedule: @schedule %>

<%= link_to 'show', @schedule %>
<%= link_to 'Back', schedule_path %>

app/views/schedules/index.html.erb
<h1>Dashboard</h1>

<h1>Schedules</h1>


<%= link_to 'New Schedule',   new_schedule_path,class: 'btn btn-primary btn-md' %>
</br>
<table class="table table-hover table-inverse">
  <thead>
  <tr>
    <th>Name</th>
    <th>Enabled?</th>
    <th>action</th>
    <th>From Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @schedule.each do |schedule| %>
      <% if schedule.user == current_user %>
      <tr>
        <td><%= schedule.name %></td>
        <td><%= schedule.enabled %></td>
        <td><%= schedule.action %></td>
        <td><%= schedule.from_time %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule_path(schedule), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>name:</strong>
  <%= @schedule.name %>
</p>

<p>
  <strong>remarks:</strong>
  <%= @schedule.remarks %>
</p>

<p>
  <strong>action:</strong>
  <%= @schedule.action %>
</p>


<p>
  <strong>snapshotid :</strong>
  <%= @schedule.snapshotid  %>
</p>

<p>
  <strong>Date time:</strong>
  <%= @schedule.dat_tme %>
</p>
<strong>Schedule was created on  <%= @schedule.from_date%>  at  <%= (@schedule.dat_tme).strftime(" %H:%M:%S")  %> </strong>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to(" Back",{:action => 'index'}) %>