config/routes.rb
Rails.application.routes.draw do
  get 'cloud_accounts/show'

  get 'cloud_accounts/new'

  get 'cloud_accounts/edit'

  get 'cloud_accounts/delete'

  get 'cloud_accounts/index'

  get 'cloud_account/index'

  devise_for :users

  resources :dashboard, only: [:index]
  resources :schedules
  resources :users, except: [:new]

  get 'rdsstart', to: 'skejulers#rdsstart'
  get 'rdsstop', to: 'skejulers#rdsstopt'
  get 'ec2start', to: 'skejulers#ec2start'
  get 'ec2stop', to: 'skejulers#ec2stop'

  root 'high_voltage/pages#show', id: 'about'
  match ':controller(/:action(/:id))',:via =>[:get, :post]

end

app/views/layouts/partials/_favicons.html.haml
%link{href: "#{asset_path('favicons/apple-icon-57x57.png')}", rel: "apple-touch-icon", sizes: "57x57"}/
%link{href: "#{asset_path('favicons/apple-icon-60x60.png')}", rel: "apple-touch-icon", sizes: "60x60"}/
%link{href: "#{asset_path('favicons/apple-icon-72x72.png')}", rel: "apple-touch-icon", sizes: "72x72"}/
%link{href: "#{asset_path('favicons/apple-icon-76x76.png')}", rel: "apple-touch-icon", sizes: "76x76"}/
%link{href: "#{asset_path('favicons/apple-icon-114x114.png')}", rel: "apple-touch-icon", sizes: "114x114"}/
%link{href: "#{asset_path('favicons/apple-icon-120x120.png')}", rel: "apple-touch-icon", sizes: "120x120"}/
%link{href: "#{asset_path('favicons/apple-icon-144x144.png')}", rel: "apple-touch-icon", sizes: "144x144"}/
%link{href: "#{asset_path('favicons/apple-icon-152x152.png')}", rel: "apple-touch-icon", sizes: "152x152"}/
%link{href: "#{asset_path('favicons/apple-icon-180x180.png')}", rel: "apple-touch-icon", sizes: "180x180"}/
%link{href: "#{asset_path('favicons/android-icon-192x192.png')}", rel: "icon", sizes: "192x192", type: "image/png"}/
%link{href: "#{asset_path('favicons/favicon-32x32.png')}", rel: "icon", sizes: "32x32", type: "image/png"}/
%link{href: "#{asset_path('favicons/favicon-96x96.png')}", rel: "icon", sizes: "96x96", type: "image/png"}/
%link{href: "#{asset_path('favicons/favicon-16x16.png')}", rel: "icon", sizes: "16x16", type: "image/png"}/
%link{href: "#{asset_path('favicons/manifest.json')}", rel: "manifest"}/
%meta{content: "#ffffff", name: "msapplication-TileColor"}/
%meta{content: "#{asset_path('favicons/ms-icon-144x144.png')}", name: "msapplication-TileImage"}/
%meta{content: "#ffffff", name: "theme-color"}/

app/views/layouts/partials/_header.html.haml
%nav.navbar.navbar-full.navbar-dark.bg-primary
  = link_to ENV['APPNAME'], root_path, class: "navbar-brand"
  %ul.nav.navbar-nav
    - unless current_user
      %li.nav-item
        = link_to 'About', page_path('about'), class: 'nav-link'
    - else
      %li.nav-item.active
        = link_to 'Dashboard', dashboard_index_path, class: 'nav-link'
        %li.nav-item.active
          = link_to 'schedules', schedules_path, class: 'nav-link'
          %li.nav-item.active
            = link_to 'Cloud account', cloud_accounts_index_path, class: 'nav-link'
        %span.sr-only (current)
  %ul.nav.navbar-nav.pull-xs-right
    - if current_user
      %li.nav-item
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'
    - else
      %li.nav-item
        = link_to 'Login', new_user_session_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'